### ISSUE TITLE
Error (403)

### ISSUE THREAD

**Issue by snikasys** [grahamr975/EWS-Office365-Contact-Sync#103]
I am testing with a single mailbox, the example batch file and a getting the following error.

Log File;
2024/02/12 17:41:10 INFO Beginning contact sync for cvxxx@mcxxx.net's mailbox
VERBOSE: Loading module from path 'C:\infowrks\EWS-Office365-Contact-Sync\EWSContacts\Module\bin\Microsoft.Exchange.WebServices.dll'.
VERBOSE: Using EWS dll from Local Directory
VERBOSE: Using Modern Auth
VERBOSE: Loading module from path 'C:\infowrks\EWS-Office365-Contact-Sync\EWSContacts\Module\bin\Microsoft.Identity.Client.dll'.
VERBOSE: GET https://login.windows.net/mcclone.net/v2.0/.well-known/openid-configuration with 0-byte payload
VERBOSE: received 1705-byte response of content type application/json; charset=utf-8
PS>TerminatingError(Get-EXCContactFolder): "Exception calling "Bind" with "2" argument(s): "The request failed. The remote server returned an error: (403) Forbidden.""
VERBOSE: Contacts not found, attempting to create now...
2024/02/12 17:41:14 FATAL Failed verify that Contacts exists for cvxxx@mcxxx.net Exception calling "Save" with "1" argument(s): "The request failed. The remote server returned an error: (403) Forbidden."
PS>TerminatingError(Write-Log): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed verify that Contacts exists for cvxxx@mcxxx.net"
>> TerminatingError(Write-Log): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed verify that Contacts exists for cvxxx@mcxxx.net"
>> TerminatingError(Write-Log): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed verify that Contacts exists for cvxxx@mcxxx.net"
>> TerminatingError(Write-Log): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed verify that Contacts exists for cvxxx@mcxxx.net"
2024/02/12 17:41:14 ERROR Failed to Sync-ContactList for cvxxx@mcxxx.net Failed verify that Contacts exists for cvxxx@mcxxx.net
**********************
Windows PowerShell transcript end
End time: 20240212174114

App Permissions;
![image](https://github.com/grahamr975/EWS-Office365-Contact-Sync/assets/160070770/e7567b29-8567-4878-bc92-6aa00659a4b6)

Any help appreciated.

**Comment by grahamr975** [comment]
Please follow the tutorial for creating the azure app in the README. You need to copy and paste the manifest code so that the application gets the EWS "full_access_as_app" permissions.
