### ISSUE TITLE
Folder not found in Mailbox

### ISSUE THREAD

**Issue by RST185** [grahamr975/EWS-Office365-Contact-Sync#13]
I have the problem that the created folder is not found in the personal contacts in the mailbox.
the public autodiscover points to Exchange Online, but it cannot find two arguments.
enclosed the error message when running the script:

FATAL Failed verify that "" exists for _"EMAILADRESS@contoso.de"_ Exception when calling "AutodiscoverUrl" with 2 argument(s): "The Autodiscover service could not be located."
Write log : Failed verify that "GAL" exists for _EMAILADRESS@contoso.de_
In line:56 characters:4

how can i solve this issue?

**Comment by grahamr975** [comment]
Are you using Office 365 online? Make sure the account has application impersonation permissions.

**Comment by grahamr975** [comment]
Closed due to inactivity.

**Comment by RST185** [comment]
Hello,

unfortunately I haven't been available lately.
the error occurs only with individual mailboxes. About 98% of the mailboxes work.
The user has the Application Impersonation Rights.

An OWA login to the faulty mailboxes is also possible.
