### ISSUE TITLE
"Access is denied" M365 with MFA

### ISSUE THREAD

**Issue by andreasmalta** [grahamr975/EWS-Office365-Contact-Sync#14]
I cannot seem to get the settings to work, but I do have the Azure Active Directory Security defaults turned on.
(https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/concept-fundamentals-security-defaults)
I'm getting the following error:

TerminatingError(New-PSSession): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: [outlook.office365.com] Connecting to remote server outlook.office365.com failed with the following error message : Access is denied. For more information, see the about_Remote_Troubleshooting Help topic."
At line:77 char:3
+         Write-Log -Level "FATAL" -Message "Failed to fetch Global Add ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log

**Comment by grahamr975** [comment]
andreasmalta,

After looking over their documentation, I've found Azure Active Directory Security defaults only supports Modern authentication. I've been working on adding modern authentication because legacy authentication is being depreciated soon. See the issue #6 for more information. https://github.com/grahamr975/EWS-Office365-Contact-Sync/issues/6 

https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/concept-fundamentals-security-defaults
> To give your users easy access to your cloud apps, Azure AD supports a variety of authentication protocols, including legacy authentication. Legacy authentication is a term that refers to an authentication request made by:
> 
> **Clients that don't use modern authentication** (for example, an Office 2010 client).

**Comment by grahamr975** [comment]
Can you try testing the new Oauth migration branch?

https://github.com/grahamr975/EWS-Office365-Contact-Sync/tree/oauth_migration

**Comment by andreasmalta** [comment]
I'm testing it, but so far with similar results. Only difference in the setup is the -ModernAuth right?

**Comment by grahamr975** [comment]
The script fails for you at Get-GalContacts.ps1, which fetches the contacts from the O365 server using [Exchange Online Powershell](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps) . I've not yet enabled ModernAuth for this portion of the script, as basic authentication for Exchange Online Powershell is not being depreciated until later in 2021. This is on my to-do list.

**Comment by Noiden** [comment]
@grahamr975 any update on this?
Thanks.

**Comment by grahamr975** [comment]
This should now be fixed with the new ModernAuthenication version of the script. Please download and install the latest version.
