### ISSUE TITLE
Only internal contacts (Users/Mailboxes) showing 

### ISSUE THREAD

**Issue by tastydoosh** [grahamr975/EWS-Office365-Contact-Sync#15]
Hi, I've been trying to get this working. I've had to tweak a few parts of it to work for what I need, but after running it's leaving a folder (with the name I specified) and the only contacts inside are those that are actual users. No contacts added to the exchange contact list appear to have synchronised. Please can you assist? :)

**Comment by grahamr975** [comment]
Use the IncludeNonUserContacts switch.

See [EWSContactSync.ps1](https://github.com/grahamr975/EWS-Office365-Contact-Sync/blob/master/EWSContactSync.ps1) for more information on the flags.

**Comment by tastydoosh** [comment]
> Use the IncludeNonUserContacts switch.
> 
> See [EWSContactSync.ps1](https://github.com/grahamr975/EWS-Office365-Contact-Sync/blob/master/EWSContactSync.ps1) for more information on the switches.

Excellent that's worked, you sir are a gentleman and a scholar, thank you!

One other question if you could possibly advise, I'm trying to get these contact folders to replicate in teams.. should that happen too? :)
