### ISSUE TITLE
ERROR Failed to Sync-ContactList

### ISSUE THREAD

**Issue by choubiket** [grahamr975/EWS-Office365-Contact-Sync#16]
Hello

I have tried multiple times to use this script but I always face the same issue, no matter the way to connect (classic or Oauth). This is the ERROR message i get : 

2020/07/29 15:59:07 INFO Beginning contact sync for XXX@XXX.COM's mailbox
EN CLAIR : Chargement du module à partir du chemin « C:\Scripts\GALSync2\EWSContacts\Module\bin\Microsoft.Exchange.WebServices.dll ».
EN CLAIR : Using EWS dll from Local Directory
EN CLAIR : Using Negotiate Auth
PS>Erreur de terminaison (Connect-EXCExchange) : « Exception lors de l'appel de « AutodiscoverUrl » avec « 2 » argument(s) : « The expected XML node type was XmlDeclaration, but the actual type is Element. » »
>> Erreur de terminaison (Connect-EXCExchange) : « Exception lors de l'appel de « AutodiscoverUrl » avec « 2 » argument(s) : « The expected XML node type was XmlDeclaration, but the actual type is Element. » »
2020/07/29 15:59:11 ERROR Failed to Sync-ContactList for XXX@XXX.com Exception lors de l'appel de « AutodiscoverUrl » avec « 2 » argument(s) : « The expected XML node type was XmlDeclaration, but the actual type is Element. »

I have the exact same error with the previous version of the script, excep with a little more details : 

2020/07/29 15:40:39 INFO Beginning contact sync for XXX@XXX.com's mailbox
EN CLAIR : Chargement du module à partir du chemin « C:\Program Files\Microsoft\Exchange\Web Services\2.2\Microsoft.Exchange.WebServices.dll ».
PS>Erreur de terminaison (Connect-EXCExchange) : « Exception lors de l'appel de « AutodiscoverUrl » avec « 2 » argument(s) : « The expected XML node type was XmlDeclaration, but the actual type is Element. » »
2020/07/29 15:40:41 FATAL Failed verify that CSH exists for XXX@XXX.com Exception lors de l'appel de « AutodiscoverUrl » avec « 2 » argument(s) : « The expected XML node type was XmlDeclaration, but the actual type is Element. »
PS>Erreur de terminaison (Write-Log) : « L’exécution de la commande s’est arrêtée, car la variable de préférence « ErrorActionPreference » ou le paramètre courant a la valeur Stop : Failed verify that CSH exists for XXX@XXX.com »
>> Erreur de terminaison (Write-Log) : « L’exécution de la commande s’est arrêtée, car la variable de préférence « ErrorActionPreference » ou le paramètre courant a la valeur Stop : Failed verify that CSH exists for XXX@XXX.com »
>> Erreur de terminaison (Write-Log) : « L’exécution de la commande s’est arrêtée, car la variable de préférence « ErrorActionPreference » ou le paramètre courant a la valeur Stop : Failed verify that CSH exists for XXX@XXX.com »
>> Erreur de terminaison (Write-Log) : « L’exécution de la commande s’est arrêtée, car la variable de préférence « ErrorActionPreference » ou le paramètre courant a la valeur Stop : Failed verify that CSH exists for XXX@XXX.com »
>> Erreur de terminaison (Write-Log) : « L’exécution de la commande s’est arrêtée, car la variable de préférence « ErrorActionPreference » ou le paramètre courant a la valeur Stop : Failed verify that CSH exists for XXX@XXX.com »
L’exécution de la commande s’est arrêtée, car la variable de préférence « ErrorActionPreference » ou le paramètre courant a la valeur Stop : Failed verify that CSH exists for XXX@XXX.com
Write-Log : Failed verify that CSH exists for XXX@XXX.com
Au caractère Ligne:56 : 4
+             Write-Log -Level "FATAL" -Message "Failed verify that $($ ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log

I have double checked and rights are fine, impersonation, script, Credentials, etc...

thanks for your feedback !

**Comment by choubiket** [comment]
Ok, I just tried to launch the script only on one Email, but also using the @OnMicrosoft.com address and this way it works... So : 

using toto@mycompany.onmicrosoft.com : OK
toot@mycompany.com : KO.

I have checked the Autodiscover on Microsoft URL and everything seems fine... 

am i missing something ? 

Thanks

**Comment by grahamr975** [comment]
@Juergen100 Thanks for providing this feedback. My environment is Exchange Online. I don't the ability to test in other environments myself at this time.

**Comment by grahamr975** [comment]
@choubiket Please try to update to the latest version. Your issue may now be fixed.
