### ISSUE TITLE
Slow to run

### ISSUE THREAD

**Issue by AtumVirt** [grahamr975/EWS-Office365-Contact-Sync#2]
The script runs without error in our environment, creates the folder for the mailbox then starts importing contacts but at a rate of about one every 4 minutes.  No errors or additional information seemed to be logged.

**Comment by grahamr975** [comment]
Removed redundant error handling from the script, along with many unneeded folder reads. Tested run time is now less than 10 seconds per contact. Please let me know if you are still having issues.
