### ISSUE TITLE
Contact sync android/ios not working

### ISSUE THREAD

**Issue by DLangenberg** [grahamr975/EWS-Office365-Contact-Sync#23]
This script was created for contact sync on android/ios but the contact sync is only working if I override the default contact folder, creating a secondary/ sub-folder works but the IOS / Android device does not sync the contacts.

is this known? or am I missing something?

**Comment by grahamr975** [comment]
See my response to issue #8. In my environment, we sync to a custom contacts folder and it shows up just fine. Try to follow the method outlined below.
> I've tested in iOS, but not Android. To sync contacts on an iPhone,
> Go to **Settings** -> **Passwords & Accounts** -> **Add Account** -> **Microsoft Exchange** -> Log in to the employee's account -> Enable contact sync for the user
> This will add all contacts, including contacts not in the default folder, to the user's iPhone.
