### ISSUE TITLE
What is CreditCardValidator.dll doing?

### ISSUE THREAD

**Issue by Noiden** [grahamr975/EWS-Office365-Contact-Sync#29]
Hi,

Thanks for a great script, I'm just wondering what this CreditCardValidator.dll is doing?

https://github.com/grahamr975/EWS-Office365-Contact-Sync/blob/master/EWSContacts/Module/bin/CreditCardValidator.dll

Thanks.

**Comment by grahamr975** [comment]
It's part of Gscale's PowerShell EWS API here: https://github.com/gscales/Powershell-Scripts/tree/master/EWSContacts

I haven't yet had the time to audit it, so I'm not exactly sure what the CreditCardValidator.dll is supposed to do.

**Comment by Noiden** [comment]
Ok, thanks for the information.

There is a script under "EWSContacts\Module\internal\functions\Find-CCNumber.ps1" that has something to do with credit cards.

**Comment by grahamr975** [comment]
Removed CreditCardValidator.dll in commit #2a65196 after verifying it's no longer used.
