### ISSUE TITLE
folder not found

### ISSUE THREAD

**Issue by Jcodedk** [grahamr975/EWS-Office365-Contact-Sync#3]
Hello

I'm getting the following error after running the script.
VERBOSE: Importing function 'Write-AdminAuditLog'.
2020/01/16 23.32.45 INFO Beginning contact sync for sherlock@nohuman.onmicrosoft.com's mailbox 
**Error Folder Not Found check path and try again**
2020/01/16 23.33.12 INFO Creating Contact: admin@nohuman.onmicrosoft.com 
Contact Created
2020/01/16 23.33.14 INFO Creating Contact: sherlock@nohuman.onmicrosoft.com 
Contact Created
2020/01/16 23.33.14 INFO Creating Contact: EWSContactSync_service@nohuman.dk 
Contact Created
Transcript stopped, output file is C:\Users\jonas.DESKTOP-U02QVVD\OneDrive\Skrivebord\EWS-Office365-Contact-Sync-master\logs\PowerShell_transcript.DESKTOP
-U02QVVD.FZkCu_R5.20200116233231.txt

**Comment by Jcodedk** [comment]
fixed. Not an error, just telling me it's creating the folder since it does not exist :)

**Comment by grahamr975** [comment]
I'll add it to my to-do list to improve this message's clarity. Creating a folder should not create an error message since it's expected behavior.

**Comment by grahamr975** [comment]
When creating a new folder, the script should now produce two messages. See below.
```
Folder Not Found
<NAME OF FOLDER> not found, attempting to create now...
```
