### ISSUE TITLE
single User sync works / DIRECTORY sync fails

### ISSUE THREAD

**Issue by mandelbrotmedia** [grahamr975/EWS-Office365-Contact-Sync#32]
Hi! 

if syncing a single user everything works.
when syncing all users with DIRECTORY flag i got the following error:

ERROR Failed to Sync-ContactList for user@mydomain.com Failed verify that MY COMPANY contacts exists for user@mydomain.com

also getting 404 and 503 errors

**Comment by grahamr975** [comment]
Does the account you're running it from have Exchange application impersonation permissions? Even with an admin account, you need this.

**Comment by mandelbrotmedia** [comment]
Yes, the account has application impersonation rights.
Found out if i run the script at 9:00 everything works fine.
if i run the script at night at 2:00 i get 404 or 503 error on every mailbox.

I think its a microsoft thing

**Comment by grahamr975** [comment]
Can you verify that the necessary Office 365 URLs are whitelisted in your environment. All Microsoft 365 Common URLs with ID#56 on the following page should be allowed: https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide

**Comment by grahamr975** [comment]
Closing due to lack of reply...
