### ISSUE TITLE
Firewall needs to make it work

### ISSUE THREAD

**Issue by alexisc182** [grahamr975/EWS-Office365-Contact-Sync#33]
Hello, if you try to use this script behind a restrictive firewall. Probably you will get an error like this:

`
Write-Log : Failed to fetch Global Address List Contacts from Office 365 Directory
En línea: 77 Carácter: 3
          Write-Log -Level "FATAL" -Message "Failed to fetch Global Add ...
       CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
       FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write
    Log
`

But if you go to: https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide

You can solve it whitelisting these domains and networks:

`*.msftidentity.com, *.msidentity.com, account.activedirectory.windowsazure.com, accounts.accesscontrol.windows.net, adminwebservice.microsoftonline.com, api.passwordreset.microsoftonline.com, autologon.microsoftazuread-sso.com, becws.microsoftonline.com, clientconfig.microsoftonline-p.net, companymanager.microsoftonline.com, device.login.microsoftonline.com, graph.microsoft.com, graph.windows.net, login.microsoft.com, login.microsoftonline.com, login.microsoftonline-p.com, login.windows.net, logincert.microsoftonline.com, loginex.microsoftonline.com, login-us.microsoftonline.com, nexus.microsoftonline-p.com, passwordreset.microsoftonline.com, provisioningapi.microsoftonline.com
20.190.128.0/18, 40.126.0.0/18, 2603:1006:2000::/48, 2603:1007:200::/48, 2603:1016:1400::/48, 2603:1017::/48, 2603:1026:3000::/48, 2603:1027:1::/48, 2603:1036:3000::/48, 2603:1037:1::/48, 2603:1046:2000::/48, 2603:1047:1::/48, 2603:1056:2000::/48, 2603:1057:2::/48`

By the way, thanks for the script!

**Comment by grahamr975** [comment]
@alexisc182,

Great find. I incorporated Microsoft's whitelist information into the Prerequisite section of the script's README and added you to the acknowledgments at the bottom.

I'm glad you've found the script useful!
