### ISSUE TITLE
Script stopped working

### ISSUE THREAD

**Issue by ohendriks-ramit** [grahamr975/EWS-Office365-Contact-Sync#37]
Hi, The script seems to stop working for me. Same tenant, tested with 2 accounts on different machines.
Below is a part of the log, but I can't seem to find what is causing it?

VERBOSE: The 'Troubleshoot-AgendaMail' command in the tmp_ddxde542.na3' module was imported, but because its name does not include an approved verb, it might be difficult to find. For a list of approved verbs, type Get-Verb.
VERBOSE: Importing function 'Troubleshoot-AgendaMail'.
VERBOSE: Importing function 'Undo-SoftDeletedMailbox'.
VERBOSE: Importing function 'Undo-SoftDeletedUnifiedGroup'.
VERBOSE: Importing function 'Update-DistributionGroupMember'.
VERBOSE: Importing function 'Update-HybridConfiguration'.
VERBOSE: Importing function 'Update-MaskingIndex'.
VERBOSE: Importing function 'Update-PublicFolderMailbox'.
VERBOSE: Importing function 'Update-Recipient'.
VERBOSE: Importing function 'Update-RoleGroupMember'.
VERBOSE: Importing function 'Update-SiteMailbox'.
VERBOSE: The 'Upgrade-DistributionGroup' command in the tmp_ddxde542.na3' module was imported, but because its name does not include an approved verb, it might be difficult to find. For a list of approved verbs, type Get-Verb.
VERBOSE: Importing function 'Upgrade-DistributionGroup'.
VERBOSE: The 'Validate-OutboundConnector' command in the tmp_ddxde542.na3' module was imported, but because its name does not include an approved verb, it might be difficult to find. For a list of approved verbs, type Get-Verb.
VERBOSE: Importing function 'Validate-OutboundConnector'.
VERBOSE: The 'Validate-RetentionRuleQuery' command in the tmp_ddxde542.na3' module was imported, but because its name does not include an approved verb, it might be difficult to find. For a list of approved verbs, type Get-Verb.
VERBOSE: Importing function 'Validate-RetentionRuleQuery'.
VERBOSE: The 'Validate-ShadowCalendar' command in the tmp_ddxde542.na3' module was imported, but because its name does not include an approved verb, it might be difficult to find. For a list of approved verbs, type Get-Verb.
VERBOSE: Importing function 'Validate-ShadowCalendar'.
VERBOSE: Importing function 'Write-AdminAuditLog'.
2021-03-19 09:35:41 INFO Beginning contact sync for XXXXX@XXXX.XX mailbox
VERBOSE: Loading module from path 'C:\EWSContacts\EWSContacts\Module\bin\Microsoft.Exchange.WebServices.dll'.
VERBOSE: Using EWS dll from Local Directory
VERBOSE: Using Modern Auth
VERBOSE: Loading module from path 'C:\EWSContacts\EWSContacts\Module\bin\Microsoft.IdentityModel.Clients.ActiveDirectory.dll'.
**********************
Windows PowerShell transcript end
End time: 20210319093610
**********************

**Comment by OfirGavish** [comment]
Did you make sure the dll files are "unblocked" as the documentation suggests?

**Comment by ohendriks-ramit** [comment]
nevermind, there was no issue. fault on my part.
