### ISSUE TITLE
DIRECTORY Error

### ISSUE THREAD

**Issue by Jcodedk** [grahamr975/EWS-Office365-Contact-Sync#4]
Hello :)

I'm getting the following error when I wish to apply the GAL to DIRECTORY.

![image](https://user-images.githubusercontent.com/14327444/72637805-60b0d000-3962-11ea-8591-30846bdab97b.png)

but works when I specify what mailbox should get GAL contacts

**Comment by grahamr975** [comment]
Thankfully, I was able to reproduce this issue on my machine. To address this, I added "-AllowClobber" to the Import-PSSession command in the Get-Mailboxes function.

![image](https://user-images.githubusercontent.com/56604984/73008378-713acd80-3ddc-11ea-834e-9db7a19d60ac.png)

**Comment by Jcodedk** [comment]
Following error is given when I choose "DIRECTORY"
![image](https://user-images.githubusercontent.com/14327444/73139101-af4d2100-406a-11ea-8d83-4ec4ff4c5230.png)

**Comment by grahamr975** [comment]
Can you include the entire transcript? (with sensitive data replaced)

**Comment by grahamr975** [comment]
Was able to reproduce, fixed with latest commit: 36f9736f8d2473953e4ffdabc8271d0b88eb3a63

Please download the latest version.
