### ISSUE TITLE
Sync only enabled user accounts

### ISSUE THREAD

**Issue by Bananovics** [grahamr975/EWS-Office365-Contact-Sync#40]
Hi Ryan!

If possible how can I reach that only AD enabled user accounts create as contacts with your script?
Currently if a user left the company and the phone number which was belinging to him/her moved to another user the same phone number will present on both contacts. Thats why I would like to create contacts only for AD enabled users as those who left the company are in disabled state.

Cheers!

**Comment by Bananovics** [comment]
Solved by myself :)

**Comment by rypto** [comment]
Hi, how did you solve this?

**Comment by Bananovics** [comment]
Hi!

I added a condition when import GAL to $contactlist.
I used 
$ContactList = Get-User -ResultSize unlimited  | Where {$_.SKUAssigned -eq "TRUE" -and $_.UserAccountControl -eq "NormalAccount"}
instead of 
$ContactList = Get-User -ResultSize unlimited

You can find these lines in EWSContacts\Module\functions\contacts\Get-GALContacts.ps1 line 53.

Cheers!

**Comment by rypto** [comment]
Thanks!
I replaced the line but get an error

Where : The term '$.SKUAssigned' is not recognized as the name of a cmdlet, function, script file, or operable program.
 Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:34
+ ... unlimited | Where {$.SKUAssigned -eq "TRUE" -and $.UserAccountControl ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: ($.SKUAssigned:String) [Where-Object], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.WhereObjectCommand

Any idea?

**Comment by Bananovics** [comment]
You can run only command
Get-User -ResultSize unlimited  | Where {$_.SKUAssigned -eq "TRUE" -and $_.UserAccountControl -eq "NormalAccount"}
in PS and check the result.
If it starts to listing user mailboxes it is good.

**Comment by Chudinnio** [comment]
Hi all,
I got same issue when i start only this command:
Get-User -ResultSize unlimited | Where {$.SKUAssigned -eq "TRUE" -and $.UserAccountControl -eq "NormalAccount"}

The result is:
Where : The term '$.SKUAssigned' is not recognized as the name of a cmdlet, function, script file, or operable program.
 Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:34
+ ... unlimited | Where {$.SKUAssigned -eq "TRUE" -and $.UserAccountControl ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: ($.SKUAssigned:String) [Where-Object], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.WhereObjectCommand

Any idea how reslove it?

**Comment by Bananovics** [comment]
Hi!

Try this:
$ContactList = Get-User -ResultSize unlimited  | Where {$_.SKUAssigned -eq "TRUE" -and $_.UserAccountControl -eq "NormalAccount"}

**Comment by Bananovics** [comment]
Hi!

There is a _ character missing after $ signs. 
For some reason Github cut it out from comment..

Attached in right format as picture.
![Screenshot 2021-11-25 081853](https://user-images.githubusercontent.com/82889286/143396871-f475ab50-7da0-4711-b1ea-835247f116f0.png)

**Comment by Chudinnio** [comment]
@Bananovics 
Thank you very much for your realy fast help! It works perfectly. We can close case.
