### ISSUE TITLE
Exclude users with "Hide from address lists"

### ISSUE THREAD

**Issue by rypto** [grahamr975/EWS-Office365-Contact-Sync#42]
Hi!
I'm executing the script with the switch -ExcludeContactWithoutPhoneNumber and it works fine but I'm also getting users that are hidden from the gal. Any ideas on how to exclude those as well?

**Comment by grahamr975** [comment]
The **ExcludeSharedMailboxContacts** switch does not sync contacts that are hidden from the GAL. I'd suggest trying out this switch as well.

**Comment by rypto** [comment]
Must open this up..
I use the script with the -ExcludeContactsWithoutPhoneNumber switch and all my 210 users get synced (as intended), including the ones hidden from GAL. (not intended)

When I add -ExcludeSharedMailboxContacts to the script it deletes a bunch of contacts leaving me with only 70 contacts

The deleted contacts are all active users with phone numbers, e-mail addresses and not shared mailboxes, and only a few are hidden from GAL

What can cause this? Any hints?
Thank you
