### ISSUE TITLE
Script stops synching contacts after 4-5 minutes 

### ISSUE THREAD

**Issue by matssss** [grahamr975/EWS-Office365-Contact-Sync#44]
Hi, 

Currently I'm trying to synchronize our GAL (around 3000 contacts) to our users contacts folder (a custom one) but it always stops after the letter "G" (which takes 4-5 minutes) to get there. The script doesn't crash but just goes to the next "mailbox" in the $MailboxList and then start importing/updating the same amount of contacts. I don't see any error in the logs.

Do you have any idea what can cause this issue? I tried to run the same script on a VM but I'm getting experiencing the same issue there.

Kind regards,
Mats

**Comment by matssss** [comment]
Hi,

Seems like it stops after I hit the 1000 contacts limit. Do you have any workaround for this (e.g. create/import in a second contact folder after it counted 1000 contacts)?

Thanks a lot!

Kind regards,
Stams

**Comment by grahamr975** [comment]
Hello Mats,

I'm able to work with over 1000 contacts in my environment just fine. If there's a terminating error with a single contact, the script will just skip to the next contact, not go to the next mailbox. Secondly, I'm not sure what you mean by the script moving to the next mailbox at "G" since it does not import in alphabetical order. Perhaps not of your contacts are being pulled in? Can you try to add the below line to EWSContactSync.PS1 to generate a file with all of your contacts to make sure there's actually 3000?

```
# Fetch list of Global Address List contacts using Office 365 Powershell
$GALContacts = Get-GALContacts -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credentials $Credential -ExcludeContactsWithoutPhoneNumber $ExcludeContactsWithoutPhoneNumber -ExcludeSharedMailboxContacts 

$ExcludeSharedMailboxContacts -IncludeNonUserContacts $IncludeNonUserContacts

**$GALContacts | Export-Csv -Path .\MyContacts.csv -NoTypeInformation**
```

**Comment by matssss** [comment]
Hi Grahamr975, 

Thanks for the reply!

I removed the last imported contact and when I rerun the script the removed contact gets deleted and the first following contact gets added into the contacts folder. When I readd the removed user, the newly added user gets deleted again and the "last" user gets added again. It seems like it just stops around 1000 contacts - I think the guy in the following article ran into the same problem: https://docs.microsoft.com/en-us/answers/questions/281934/powershell-script-on-exchange-server-returns-800-r.html

I included the export-csv line but it outputs something else than a contact-list.
![2021-08-03 17_01_05-Window](https://user-images.githubusercontent.com/6841515/128038549-56008f31-d074-4d9e-a964-29ed5f2d0ccc.png)

Kind regards,
Mats

**Comment by matssss** [comment]
Hi Grahamr975,

I have noticed that the "fix" in the link I shared is already implemented in your script so that can't be the problem.
Today I tried to upper the throtthling limit and rerun the script on a new account in a new directory but unfortunately it keeps stopping after the amount of contacts.

Do you have any more troubleshooting steps?

Thanks a lot!

Kind regards,
Mats

**Comment by grahamr975** [comment]
Please use try the below line to generate a CSV file of contacts instead of the previous one I sent you.

`$GALContacts | Select-Object WindowsEmailAddress | Out-File -FilePath ".\MyContacts.csv"`

**Comment by matssss** [comment]
Hi Grahamr,

The content I get in my export is exactly the amount of contacts that always gets imported. 
![2021-08-05 08_38_05-export](https://user-images.githubusercontent.com/6841515/128303653-74923f99-4620-415c-aa43-6232f69c4359.png)

Kind regards,
Mats

**Comment by matssss** [comment]
Hi Grahamr,

Something I noticed today while running the script:
WARNING: By default, only the first 1000 items are returned. Use the ResultSize parameter to specify the number of
items returned. To return all items, specify "-ResultSize Unlimited". Be aware that, depending on the actual number of
items, returning all items can take a long time and consume a large amount of memory. Also, we don't recommend storing
the results in a variable. Instead, pipe the results to another task or script to perform batch changes.

 I checked the functions but don't really where the above is missing. Do you have any idea?

Thanks a lot!

Kind regards,
Mats

**Comment by grahamr975** [comment]
Hello Mats,

Thanks for generating the contact list. The CSV shows us that the script is only fetching approximately 1000 contacts from your environment's Global Address List. This helps us narrow down the issue. Can you please verify that line 53 of Get-GALContacts.ps1 contains **-ResultSize unlimited**? It should be the below, but perhaps you may have accidentally remove part of the line.

`$ContactList = Get-User -ResultSize unlimited `

Secondly, where are you getting this 3000 number from? This script only fetches Azure users in your environment. It does not include on-premise only users at this time. Can you try including -IncludeNonUserContacts as a flag in the script? This additionally syncs contacts that aren't actual mailboxes.

**Comment by matssss** [comment]
Hi Grahamr,

I checked line 53, it contains "-ResultSize unlimited".

Here you see a screenshot of the amount of mail contacts:
![2021-08-05 16_42_26-contacts - Microsoft Exchange](https://user-images.githubusercontent.com/6841515/128369797-e68688e3-9dc4-4e54-9970-9eddc16d2327.png)

When I set -IncludeNonUserContacts to $false, I only get around 60 contacts, which is right.

Kind regards,
Mats

**Comment by grahamr975** [comment]
Mats,

I found a bug with the code and applied hotfix bcbcaea11415cc3e74a1a0de45cc2e9fc9757bd5 because when using the -IncludeNonUserContacts flag, only up to 1000 additional non-user contacts could be returned. Can you please try to download the latest version and let me know if this resolves your issue? Thanks

**Comment by matssss** [comment]
Hi Grahamr,

Thanks a lot, it works now!

Thanks for troubleshooting this so quickly. Have a great day!

Kind regards,
Mats
