### ISSUE TITLE
Request: Validation on Phone number

### ISSUE THREAD

**Issue by Jcodedk** [grahamr975/EWS-Office365-Contact-Sync#5]
Hello

Possible to validate if the contact has a "Phone number" in any kind
if yes 
SYNC to the contacts folder
if no
Throw.

So we don't end up with service accounts with no phone number

**Comment by Jcodedk** [comment]
Hello inside
Sync-ContactList.ps1 I made following to accomplish my own enhancement
![image](https://user-images.githubusercontent.com/14327444/72821296-9d394000-3c70-11ea-9145-dbd64b24c6c5.png)

**Comment by grahamr975** [comment]
Nice job, Jcodedk. I like your initiative.

I've updated the script to include your feature using a slightly more efficient method. This was accomplished by modifying the Get-GALContacts.ps1 function. To use this new feature, please run EWSContactSync.ps1 with the RequirePhoneNumber switch.

![image](https://user-images.githubusercontent.com/56604984/72834440-da90d400-3c56-11ea-9963-471a8dd18ebf.png)
