### ISSUE TITLE
ModernAuth Update

### ISSUE THREAD

**Issue by benj288** [grahamr975/EWS-Office365-Contact-Sync#56]
Hello,

i currently can't get the Contacts List and also can't execute the Contact Sync due to Basic auth deactivation. (Errors in particular: "Can't fetch Data" "Autodiscover failed")
Is there a way, to update the Script, without making a Azure AD App?
Thank you
Kind regards

**Comment by grahamr975** [comment]
@benj288 

Are you using the -ModernAuth flag?

**Comment by benj288** [comment]
Yes, i get this error however, when the script is trying to fetch the Contact info
![image](https://user-images.githubusercontent.com/105342091/178274310-9d22d63b-88b5-42dc-8bff-142f86bfe39c.png)

**Comment by benj288** [comment]
I have so far resolved the issue regarding the fetching of the Contact info after implementing an Azure app and adapting the Get-GALContacts Module (Issue #46)
However, I get following error when it is trying to Sync to the Mailbox.

VERBOSE: Loading module from path 'C:\Kontaktesynchronisierung\Skripts\SyncModul\EWSContacts\Module\bin\Microsoft.IdentityModel.Clients.ActiveDirectory.dll'.
PS>TerminatingError(Connect-EXCExchange): "Exception calling "AutodiscoverUrl" with "2" argument(s): "The Autodiscover service couldn't be located.""
>> TerminatingError(Connect-EXCExchange): "Exception calling "AutodiscoverUrl" with "2" argument(s): "The Autodiscover service couldn't be located.""
2022.07.18 15:27:13 ERROR Kontakte Sync fehlgeschlagen fuer Mail@mycompany.com Exception calling "AutodiscoverUrl" with "2" argument(s): "The Autodiscover service couldn't be located."

Is there a updated version of the Connect-EXCExchange Module and the Sync-ContactList module?

**Comment by christianneeb** [comment]
Which version of PowerShell you are using? 

Can you try to run this command prior and then try again? I currently using PowerShell 4.0 on Server 2012 R2 and this helped me

`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`

**Comment by benj288** [comment]
Sorry for not responding on this issue - haven't had the time to do so
Have you adjusted the Connect-Exchange.ps1 in any way? Or added your App Details somewhere else too?
I have traced my errors back to either the Azure App or something in the Script.
If you register a new App, you can't select "Exchange" anymore, just the Graph. The roles for the apps have also been removed.
If you'd be so kind, could you share me your current working Script and App? I dont need your confidential data though ;)
Kind regards
Ben

**Comment by benj288** [comment]
> Which version of PowerShell you are using?
> 
> Can you try to run this command prior and then try again? I currently using PowerShell 4.0 on Server 2012 R2 and this helped me
> 
> `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`

Where have you added this line?

**Comment by benj288** [comment]
Sorry for writing again - i have made our script finally work. 
However, in my Azure AD Sign-in logs, there is still an entry coming up from the script. Since basic auth will be disabled on October 1st, i need to adjust the script to this.

My only problem is the Sync-ContactList.ps1
Has anyone adjusted this script for an Azure APP? If so, could you please share this with me? I would be grateful.

Kind regards
Ben

**Comment by grahamr975** [comment]
@benj288 Could you source the website where you found the basic authentication depreciation date? I thought it was next year, rather than October 1st. Thanks

**Comment by christianneeb** [comment]
> @benj288 Could you source the website where you found the basic authentication depreciation date? I thought it was next year, rather than October 1st. Thanks

You will find the informations here: https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online

**Comment by benj288** [comment]
Yes they announced it last year
Did anybody adjust their scripts?

**Comment by benj288** [comment]
@christianneeb Where have you added the
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
In your Scripts?

**Comment by grahamr975** [comment]
@benj288 Several users have had success with setting up an Azure app for ExchangeOnline in issue #46. I'm working on an update for the main script with a tutorial for setting this up.

As for the EWS portion of the script, I don't think this needs to be changed as it's already coded to generate an OAuth token from the user credentials when using the -ModernAuth flag.

**Comment by benj288** [comment]
> @benj288 Several users have had success with setting up an Azure app for ExchangeOnline in issue #46. I'm working on an update for the main script with a tutorial for setting this up.
> 
> As for the EWS portion of the script, I don't think this needs to be changed as it's already coded to generate an OAuth token from the user credentials when using the -ModernAuth flag.

Thank you for your info. Is there new version of the Main script working?

**Comment by grahamr975** [comment]
@benj288 I'm still working on the new version + a guide for setting up a cert. Once it's available, I'll publish it for everyone.

**Comment by grahamr975** [comment]
@benj288 and others,

I published the new OAuth script version & guide in commit 9fcfe1f06192848882564615dd9aa05e71d69970. All basic authentication has been upgraded to modern. If anyone has any questions, please reach out.
