### ISSUE TITLE
Fix for Modernauth -ExcludeSharedMailboxContacts

### ISSUE THREAD

**Issue by Snake98bm** [grahamr975/EWS-Office365-Contact-Sync#58]
After applying the fix from [JimSnead](https://github.com/JimSnead) here

https://github.com/grahamr975/EWS-Office365-Contact-Sync/issues/56#issuecomment-1198509331

I couldn't use the  -ExcludeSharedMailboxContacts flag.  Here is orginal code from JimSnead

            $DirectoryList = $(Get-EXOMailbox -ResultSize unlimited | Where-Object {$_.HiddenFromAddressListsEnabled -Match "False"})

			$EmailAddressList = $DirectoryList.PrimarySMTPAddress
			$ContactList = $ContactList | Select-Object DisplayName,FirstName,LastName,Title,Company,Department,WindowsEmailAddress,Phone,MobilePhone | Where-Object {$EmailAddressList.Contains($_.WindowsEmailAddress)}
		} else {
			$ContactList = $ContactList | Select-Object DisplayName,FirstName,LastName,Title,Company,Department,WindowsEmailAddress,Phone,MobilePhone
		}
Here is the fix for the code.

            $DirectoryList = $(Get-EXOMailbox -ResultSize unlimited -PropertySets Minimum,AddressList | Where-Object {$_.HiddenFromAddressListsEnabled -Match "False"})

			$EmailAddressList = $DirectoryList.PrimarySMTPAddress
			$ContactList = $ContactList | Select-Object DisplayName,FirstName,LastName,Title,Company,Department,WindowsEmailAddress,Phone,MobilePhone | Where-Object {$EmailAddressList.Contains($_.WindowsEmailAddress)}
		} else {
			$ContactList = $ContactList | Select-Object DisplayName,FirstName,LastName,Title,Company,Department,WindowsEmailAddress,Phone,MobilePhone
		}

Sorry couldn't do a pull request.

**Comment by grahamr975** [comment]
@Snake98bm thanks for posting this
