### ISSUE TITLE
Error: Basic authentication is currently disabled in the client configuration. 

### ISSUE THREAD

**Issue by AdmiralNosnevets** [grahamr975/EWS-Office365-Contact-Sync#60]
Good Afternoon, 

First, thanks for the script, it is a lifesaver and much needed. I'm fairly new to scripting and have run into some issues. I am using the application method and have been able to follow the guide giving the app all the permissions needed. I am able to generate the pfx and cer files no problem. When i go to generate the export clixml it always generates an xml file. In your example batch file you show this as a .cred file not .xml. should i be generating a .cred? Do I just change the filename or is .xml correct? I have been using the .xml and have been getting an error no matter how many times I go through the instructions. 

**The WinRM client cannot process the request. Basic authentication is currently disabled in the client configuration. Change the client configuration and try the request again.**

I am using the Modernauth flag. basic auth is disabled through gpo but since this is using cert and modern auth flag I figured that shouldn't matter. 

Here is my anonymized batch. 

@echo off
cd "script directory"

PowerShell.exe -ExecutionPolicy Bypass ^
-File "C:\Users\jappleseed\OneDrive - apple\Documents\Projects\GAL Sync\EWSContactSync.ps1" ^
-CertificatePath "C:\Users\jappleseed\OneDrive - apple\Documents\Projects\GAL Sync\mycert.pfx" ^
-CertificatePasswordPath "C:\Users\jappleseed\OneDrive - apple\Documents\Projects\GAL Sync\SecureCertificatePassword.xml" ^
-ClientID "0d79f13d-anon-Hippopatamus" ^
-FolderName "C:\Users\jappleseed\OneDrive - apple\Documents\Projects\GAL Sync\CFILE" ^
-LogPath "C:\Users\jappleseed\OneDrive - apple\Documents\Projects\GAL Sync\Log" ^
-MailboxList JAppleseed@apple.com ^
-ExchangeOrg "apple.onmicrosoft.com" ^
-ModernAuth
pause

Any Ideas?

**Comment by grahamr975** [comment]
1. Exchange Powershell v2 requires client-side basic authentication on the host computer in order for WinRM to work. Don't worry -- OAuth is still used on the server-side. [Can you please follow this tutorial to enable WinRM on your computer?](https://learn.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#turn-on-basic-authentication-in-winrm) Let me know how this works for you.

3. The FolderName parameter needs to be just the name of the contacts folder that will be created in Exchange, such as "Company Contacts".

**Comment by AdmiralNosnevets** [comment]
@grahamr975 Thanks for the link, It got me going. I had seen it but since basic auth is going away I didn't use it. Our security guy is still noping the basic auth even if local. Does EXO V3 module provide any hope for going full certificate based? Once again thanks for the help!

**Comment by grahamr975** [comment]
@AdmiralNosnevets

Microsoft is not depreciating WinRM. [See the article here for more info on this.](https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online#exchange-online-powershell) The script is already fully certificate-based & does not rely on any user credentials. You can try EXO V3 but you would need to make some tweaks within the script in order to use it. Sorry, but I don't have plans to upgrade the script to EXO v3 so I can't provide further direction on this.
