### ISSUE TITLE
Cannot convert the "System.Management.Automation.PSCredential

### ISSUE THREAD

**Issue by S-Mellado** [grahamr975/EWS-Office365-Contact-Sync#66]
I have problem when I execute .bat, the error message said Cannot convert the "System.Management.Automation.PSCredential" value of type "System.Management.Automation.PSCredential" to type "System.Security.SecureString".
I think my problem is with the certificates in my .bat (certificatepath and certificatepasswordpath):

![image](https://user-images.githubusercontent.com/116640489/197752785-dc37dc5a-1a9a-4a16-9636-38d46797d922.png)

How can I generate or from where I generate the .pfx and .cred?  I use the Create-SecureCertificatePassword.ps1, but... I have a mistake.

![image](https://user-images.githubusercontent.com/116640489/197753254-bd15126f-1954-4165-864a-d6632fa4aa71.png)

Thanks for your support!

**Comment by Manuel-Yotta** [comment]
Hi, I have the same problem. How can I solve?
Thanks for your support!

**Comment by S-Mellado** [comment]
Hi, review Get-GALContacts.ps1 script and in the line _Connect-ExchangeOnline -ConnectionUri $ConnectionUri -CertificateFilePath $CertificatePath -CertificatePassword $CertificatePassword -AppId $ClientID -Organization $ExchangeOrg_ add this parameter **-UseRPSSession**  like this: **_Connect-ExchangeOnline -UseRPSSession -ConnectionUri $ConnectionUri -CertificateFilePath $CertificatePath -CertificatePassword $CertificatePassword -AppId $ClientID -Organization $ExchangeOrg_** 

Let me know if all is ok.

**Comment by Manuel-Yotta** [comment]
> 

Hi and thanks,
unfortunately it does not change

![immagine](https://user-images.githubusercontent.com/100789900/200596738-a4798ffb-c691-4d12-92e2-35b1eec131a1.png)

**Comment by S-Mellado** [comment]
Do you review the permission on the azure app?
![image](https://user-images.githubusercontent.com/116640489/200597163-611fde9c-3343-44fd-ba94-40bde69c085f.png)

**Comment by Manuel-Yotta** [comment]
Yes:

![immagine](https://user-images.githubusercontent.com/100789900/200598285-d39bd2ab-9271-4b62-9ea5-f26f56a77dce.png)

**Comment by S-Mellado** [comment]
Try this. Change the .bat by powershell. Forget .bat.
Open powershell and call to your ps1, like this: 

_$CertificatePath = "C:\Admin\Scripts\Contacts_New\Certificados\Certificate.pfx"
$CertificatePasswordPath = "C:\Admin\Scripts\Contacts_New\Getting Started\SecureCertificatePassword.xml"
$ClientID = "CLientID" (write your client id)
$FolderContacName = "FolderName"
$LogPath = "%~dp0Logs"
$ExchangeOrg = "contoso.onmicrosoft.com"
function Get-Buzon
{
  param
  (
    $MailBox = $(
      Write-Host ' '
      Write-Host '*************************** SCRIPT CONTACTOS ********************************** '
      Write-Host ' '
      Write-Host 'Script para desplegar los contactos de la compañía sobre el buzón de un usuario '
      Write-Host 'Se guardarán en una carpeta de los contactos del usuario llamada Deoleo Mobile'
      Write-Host ' '
      Write-Host '******************************************************************************* '
      Write-Host ' '
      Write-Host 'Introduzca el buzón del usuario: '-ForegroundColor Yellow -NoNewLine
      Read-Host 
    )
  )
    
  $MailBox
}
$MailBox = Get-Buzon

C:\Admin\Scripts\Contacts_New\EWSContactSync.ps1 -CertificatePath $CertificatePath -CertificatePasswordPath $CertificatePasswordPath -ClientID $ClientID -FolderName $FolderContacName -LogPath $LogPath -MailboxList $MailBox -ExchangeOrg $ExchangeOrg -ModernAuth_

**Comment by Manuel-Yotta** [comment]
I'm sorry but I didn't understand how to proceed

Thanks

Manuel Montesano

Da: S-Mellado ***@***.***>
Inviato: martedì 8 novembre 2022 16:04
A: grahamr975/EWS-Office365-Contact-Sync ***@***.***>
Cc: Manuel Montesano ***@***.***>; Comment ***@***.***>
Oggetto: Re: [grahamr975/EWS-Office365-Contact-Sync] Cannot convert the "System.Management.Automation.PSCredential (Issue #66)


Try this. Change the .bat by powershell. Forget .bat.
Open powershell and call to your ps1, like this:

_$CertificatePath = "C:\Admin\Scripts\Contacts_New\Certificados\Certificate.pfx"
$CertificatePasswordPath = "C:\Admin\Scripts\Contacts_New\Getting Started\SecureCertificatePassword.xml"
$ClientID = "CLientID" (write your client id)
$FolderContacName = "FolderName"
$LogPath = "%~dp0Logs"
$ExchangeOrg = "contoso.onmicrosoft.com"
function Get-Buzon
{
param
(
$MailBox = $(
Write-Host ' '
Write-Host '*************************** SCRIPT CONTACTOS ********************************** '
Write-Host ' '
Write-Host 'Script para desplegar los contactos de la compañía sobre el buzón de un usuario '
Write-Host 'Se guardarán en una carpeta de los contactos del usuario llamada Deoleo Mobile'
Write-Host ' '
Write-Host '******************************************************************************* '
Write-Host ' '
Write-Host 'Introduzca el buzón del usuario: '-ForegroundColor Yellow -NoNewLine
Read-Host
)
)

$MailBox
}
$MailBox = Get-Buzon

C:\Admin\Scripts\Contacts_New\EWSContactSync.ps1 -CertificatePath $CertificatePath -CertificatePasswordPath $CertificatePasswordPath -ClientID $ClientID -FolderName $FolderContacName -LogPath $LogPath -MailboxList $MailBox -ExchangeOrg $ExchangeOrg -ModernAuth_

**Comment by Manuel-Yotta** [comment]
> Try this. Change the .bat by powershell. Forget .bat. Open powershell and call to your ps1, like this:
> 
> **$CertificatePath = "C:\Admin\Scripts\Contacts_New\Certificados\Certificate.pfx" $CertificatePasswordPath = "C:\Admin\Scripts\Contacts_New\Getting Started\SecureCertificatePassword.xml" $ClientID = "CLientID" (write your client id) $FolderContacName = "FolderName" $LogPath = "%~dp0Logs" $ExchangeOrg = "contoso.onmicrosoft.com" function Get-Buzon { param ( MailBox=( Write-Host ' ' Write-Host '*************************** SCRIPT CONTACTOS ********************************** ' Write-Host ' ' Write-Host 'Script para desplegar los contactos de la compañía sobre el buzón de un usuario ' Write-Host 'Se guardarán en una carpeta de los contactos del usuario llamada Deoleo Mobile' Write-Host ' ' Write-Host '******************************************************************************* ' Write-Host ' ' Write-Host 'Introduzca el buzón del usuario: '-ForegroundColor Yellow -NoNewLine Read-Host ) ) $MailBox } $MailBox = Get-Buzon
> 
> C:\Admin\Scripts\Contacts_New\EWSContactSync.ps1 -CertificatePath $CertificatePath -CertificatePasswordPath $CertificatePasswordPath -ClientID $ClientID -FolderName $FolderContacName -LogPath $LogPath -MailboxList $MailBox -ExchangeOrg $ExchangeOrg -ModernAuth**

I'm sorry but I didn't understand how to proceed

**Comment by grahamr975** [comment]
@Manuel-Yotta Can you try to change your system language to English so see if this resolves your issue? I've not tested the script in other languages.

**Comment by grahamr975** [comment]
@Manuel-Yotta 

It looks like you exported your certificate password using "Get-Credential". You need to instead use "Read-Host -AsSecureString" to export the password. See below for an example.

```
# interactively prompt for the credential
$SecureString = Read-Host -AsSecureString

# export the secret string object to a file
$SecureString | Export-Clixml .\SecureCertificatePassword.cred
```

**Comment by Manuel-Yotta** [comment]
> `# interactively prompt for the certificate password as a secure string`

perfect, I confirm that this solution is decisive. 
Thanks so much everyone for the support and congratulations again for the script!!!

**Comment by grahamr975** [comment]
Reported as solved, closing issue...
