### ISSUE TITLE
Failed to fetch Global Address List Contacts from Office 365 Directory

### ISSUE THREAD

**Issue by rypto** [grahamr975/EWS-Office365-Contact-Sync#68]
Hi,

I'm sure I'm doing something wrong. I get the following when testing the script to only one user. What could be the issue?
![image](https://user-images.githubusercontent.com/35531740/201101718-e874c71b-cb34-4cb3-837e-5209501cce74.png)

**Comment by rypto** [comment]
I added -UseRPSSession to line 57 in Get-GALContacts.ps1 and it works now

`# Connect to Office 365 Exchange Server using a Remote Session
        Connect-ExchangeOnline **-UseRPSSession** -ConnectionUri $ConnectionUri -CertificateFilePath $CertificatePath -CertificatePassword $CertificatePassword -AppId $ClientID -Organization $ExchangeOrg`

**Comment by AisaacOcean** [comment]
Hi, I am also running it for a single user and I get the same problem.

I have tried what Rypto said but I get the same error.

Why is this error occurring?

**Comment by grahamr975** [comment]
It looks like you're using Exchange Online version 3.0. You need to use version 2.5 with the script. Please see the README.

**Comment by rypto** [comment]
Indeed, sorry for not checking. Using version 2.0.5 solved the problem and other problems related to the switches as well.
So using version 2.0.5 you don't need to use that string I provided above
