### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by AisaacOcean** [grahamr975/EWS-Office365-Contact-Sync#71]
Hello,

Can you please confirm that you're using ExchangeOnlineManagement version 2.0.5?

Thanks

_Originally posted by @grahamr975 in https://github.com/grahamr975/EWS-Office365-Contact-Sync/issues/70#issuecomment-1332195447_

**Comment by AisaacOcean** [comment]
close

**Comment by AisaacOcean** [comment]
close

**Comment by grahamr975** [comment]
Yes, please version 2.0.5. Do not use version 3.0.
