### ISSUE TITLE
Contacts only seen on mobile if in "default contact" folder

### ISSUE THREAD

**Issue by Jcodedk** [grahamr975/EWS-Office365-Contact-Sync#8]
Hello :) 

Are you aware that contacts who are not in the "default contacts" is not seen on IOS/Android?

Right now I don't see any of my contacts from my custom folder(created with the script) to appear in my native contact app.
Sync/save is enabled inside Outlook (Mobile app)

**Comment by Jcodedk** [comment]
Any possible way we could add the contacts to the default created contact folder that comes with a mailbox? "Your contacts"

**Comment by grahamr975** [comment]
I've tested in iOS, but not Android. To sync contacts on an iPhone,
Go to Settings -> Passwords & Accounts -> Add Account -> Microsoft Exchange -> Log in to the employee's account -> Enable Contact Sync
This will add all contacts, including contacts not in the default folder, to the user's iPhone.

I could implement your suggestion; however, any Outlook contacts that the employees add would be overwritten/deleted by the script. I'd strongly advise you create a separate folder.

**Comment by Jcodedk** [comment]
I understand.

But I am using the Outlook app since the "company" user would probably use Outlook (with CA, only use Cloud approved apps) together with APP(App Protection Policies). 
And the Outlook app only looks inside the default folder - Would it be possible to have this feature?
