### ISSUE TITLE
ExcludeSharedMailboxContacts excluding many (real) Users

### ISSUE THREAD

**Issue by Robs90** [grahamr975/EWS-Office365-Contact-Sync#80]
When using the Parameter ExcludeSharedMailboxContacts, some Users get excluded even though they are returned by Get-EXOMailbox and are present in the Variable $Contactlist.

We found that the comparison between the results of Get-EXOMailbox and $Contactlist is Case sensitive. This results in excluding a User, when the WindowsEmailAddress is written using Capital Letters (First.Lastname@Domain.com) and the PrimarySMTPAddress is written in lower Case (first.lastname@domain.com). The script does not see a Match, and this User is skipped in the Contact List.

We found that when using the parameter ExcludeSharedMailboxContacts, the following line (Line 66 of Get-GALContacts.ps1) should be changed:

OLD (skipping Users where the Case does not match):

_$ContactList = $ContactList | Select-Object DisplayName,FirstName,LastName,Title,Company,Department,WindowsEmailAddress,Phone,MobilePhone | Where-Object {$EmailAddressList.Contains($_.WindowsEmailAddress)}

NEW (which ignores the Case in which the Emailaddress is written):

_$ContactList = $ContactList | Select-Object DisplayName,FirstName,LastName,Title,Company,Department,WindowsEmailAddress,Phone,MobilePhone | Where-Object {$EmailAddressList -Contains $_.WindowsEmailAddress}

Using the Contains Parameter in the second format, is not Case Sensitive. The Functionality however stays the same.

**Comment by grahamr975** [comment]
@Robs90 

Thanks for the detailed breakdown. This logic makes sense. When I have time, I will test and push this commit.

Ryan

**Comment by koreytm** [comment]
Great find, @Robs90 !

**Comment by christianneeb** [comment]
Same issue was posted about a year ago incl another solution
#55

**Comment by grahamr975** [comment]
Addressed by latest commit...
