### ISSUE TITLE
FATAL Failed to fetch Global Address List Contacts from Office 365 Directory Expired or Invalid pagination request. Default Expiry time is 00:30:00

### ISSUE THREAD

**Issue by StevenVBeek** [grahamr975/EWS-Office365-Contact-Sync#81]
Hello,

I encountered an error while attempting to retrieve all the information for the GAL list. The error message reads as follows: "FATAL Failed to fetch Global Address List Contacts from Office 365 Directory Expired or Invalid pagination request. Default Expiry time is 00:30:00."

Initially, I was able to connect Exchange Online with my user account successfully. However, the error occurred after I received 440 contacts out of a total of 3360 when i connected with certificate. Do you have any suggestions for resolving this issue?

**Comment by grahamr975** [comment]
What version of Exchange Powershell are you using?
