### ISSUE TITLE
EWSContactSync.ps1 : Cannot convert the "System.Management

### ISSUE THREAD

**Issue by thomasjgithub** [grahamr975/EWS-Office365-Contact-Sync#90]
I have followed the instructions, but I do get an error while running the *.bat-file. - any suggestion on this error:

***\EWSContactSync.ps1 : Cannot convert the "System.Management.Automation.PSCredential" value of type "System.
Management.Automation.PSCredential" to type "System.Security.SecureString".
    + CategoryInfo          : MetadataError: (:) [EWSContactSync.ps1], ArgumentTransformationMetadataException
    + FullyQualifiedErrorId : RuntimeException,EWSContactSync.ps1

It might be that I have messed up while running the Create-SecureCertificatePassword.ps1 and Creat-SecureCredential.ps1 (as it lack instruction in the ReadMe-section).

**Comment by grahamr975** [comment]
@thomasjgithub 

You need to use the Create-SecureCertificatePassword.ps1 script for storing the certificate password, looks like you used the Create-SecureCredential.ps1 one. I will work on clarifying this in the documentation.

**Comment by grahamr975** [comment]
Removed obsolete Create-SecureCredential.ps1 file, closing ticket...
