### ISSUE TITLE
Duplicate Contacts in Folder

### ISSUE THREAD

**Issue by swilly23** [grahamr975/EWS-Office365-Contact-Sync#98]
When I was scheduling this script to run as a task and test, it ended up running twice with overlap. The result is that a majority of the contacts are listed twice in the contacts folder. 

Is there a way to remove duplicates and/or prevent this from happening again?

**Comment by grahamr975** [comment]
Hello, the script is only meant to run one instance at a time. Running it again should clean up the duplicates
